entities: 
    basic:
        name: Entity
        attributes:
            health: 100
            mana: 100
        abilities:
            - inherits: attack
            - inherits: heal
            - inherits: dot
    entity1:
        inherits: basic
        name: Entity 1
    entity2:
        inherits: basic
        name: Entity 2
    entity3:
        inherits: basic
        name: Entity 3
    entity4:
        inherits: basic
        name: Entity 4
abilities:
    attack:
        name: Attack
        effects:
            - inherits: damage
              duration: 0
    heal:
        name: Heal
        effects:
            - inherits: heal
              duration: 0
    dot:
        name: Damage Over Time
        effects: 
            - inherits: damage
              duration: 10
    hot:
        name: Heal Over Time
        effects:
            - inherits: heal
              duration: 10
attributes:
    health:
        name: Health
        min: 0
        max: 1000
    mana:
        name: Mana
        min: 0
        max: 100
effects:
    damage: 
        duration: 0
        modifiers:
            - attribute: health
              value: -10
    heal: 
        duration: 0
        modifiers:
            - attribute: health
              value: 10  
            

